[package]
name = "rat-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.42"
aya = { version = ">=0.11", features = ["async_tokio"] }
aya-log = "0.1"
bytes = "1"
clap = { version = "3.1", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

[[bin]]
name = "rat-rs"
path = "src/main.rs"
